
import { Form } from './types';

export const mockForms: Form[] = [
  {
    id: '1',
    name: 'Hợp đồng lao động thời vụ',
    description: 'Mẫu hợp đồng lao động thời vụ theo quy định mới nhất của Bộ LĐ-TB&XH áp dụng từ Q1/2025',
    category: 'Nhân sự và Lao động',
    status: 'Đang sử dụng',
    version: '2.1',
    author: 'Nguyễn Thị A',
    effectiveFrom: '01/01/2025',
    effectiveTo: '31/12/2025',
    updatedAt: '15/03/2025',
    isFavorite: true,
  },
  {
    id: '2',
    name: 'Biên bản vi phạm hành chính',
    description: 'Biên bản ghi nhận vi phạm hành chính trong doanh nghiệp, áp dụng cho mọi phòng ban',
    category: 'Quản trị Doanh nghiệp',
    status: 'Đang sử dụng',
    version: '1.0',
    author: 'Trần Văn B',
    effectiveFrom: '01/02/2025',
    effectiveTo: '31/12/2025',
    updatedAt: '01/02/2025',
    isFavorite: false,
  },
  {
    id: '3',
    name: 'Phụ lục hợp đồng tăng lương',
    description: 'Phụ lục điều chỉnh mức lương và phụ cấp trong hợp đồng lao động',
    category: 'Nhân sự và Lao động',
    status: 'Đang sử dụng',
    version: '3.2',
    author: 'Lê Thị C',
    effectiveFrom: '01/03/2025',
    effectiveTo: '31/12/2025',
    updatedAt: '28/02/2025',
    isFavorite: true,
  },
  {
    id: '4',
    name: 'Giấy ủy quyền đại diện',
    description: 'Mẫu giấy ủy quyền cho người đại diện theo pháp luật của công ty',
    category: 'Pháp lý và Giấy phép',
    status: 'Đang sử dụng',
    version: '2.0',
    author: 'Phạm Văn D',
    effectiveFrom: '15/01/2025',
    effectiveTo: '15/01/2026',
    updatedAt: '10/01/2025',
    isFavorite: false,
  },
  {
    id: '5',
    name: 'Biên bản họp HĐQT',
    description: 'Mẫu biên bản cuộc họp Hội đồng quản trị theo quy định của Điều lệ công ty',
    category: 'Quản trị Doanh nghiệp',
    status: 'Đang sử dụng',
    version: '1.5',
    author: 'Hoàng Thị E',
    effectiveFrom: '01/01/2025',
    effectiveTo: '31/12/2025',
    updatedAt: '05/01/2025',
    isFavorite: false,
  },
  {
    id: '6',
    name: 'Hợp đồng mua bán hàng hóa',
    description: 'Mẫu hợp đồng mua bán hàng hóa áp dụng cho giao dịch trong nước',
    category: 'Khách hàng, đối tác và Hợp đồng',
    status: 'Đang sử dụng',
    version: '3.0',
    author: 'Vũ Văn F',
    effectiveFrom: '01/03/2025',
    effectiveTo: '01/03/2026',
    updatedAt: '25/02/2025',
    isFavorite: true,
  },
  {
    id: '7',
    name: 'Bảng kê chi phí công tác',
    description: 'Mẫu bảng kê chi phí công tác phát sinh trong quá trình làm việc ngoài công ty',
    category: 'Tài chính - Kế toán',
    status: 'Đang sử dụng',
    version: '2.3',
    author: 'Đỗ Thị G',
    effectiveFrom: '01/01/2025',
    effectiveTo: '31/12/2025',
    updatedAt: '28/12/2024',
    isFavorite: false,
  },
  {
    id: '8',
    name: 'Đơn xin nghỉ phép',
    description: 'Mẫu đơn xin nghỉ phép tiêu chuẩn áp dụng cho mọi nhân viên công ty',
    category: 'Nhân sự và Lao động',
    status: 'Sắp hết hạn',
    version: '1.0',
    author: 'Ngô Văn H',
    effectiveFrom: '01/01/2025',
    effectiveTo: '30/04/2025',
    updatedAt: '01/01/2025',
    isFavorite: false,
  },
  {
    id: '9',
    name: 'Hợp đồng thử việc',
    description: 'Mẫu hợp đồng áp dụng cho nhân viên trong giai đoạn thử việc',
    category: 'Nhân sự và Lao động',
    status: 'Đang sử dụng',
    version: '2.1',
    author: 'Lý Thị I',
    effectiveFrom: '01/02/2025',
    effectiveTo: '31/12/2025',
    updatedAt: '25/01/2025',
    isFavorite: false,
  },
  {
    id: '10',
    name: 'Hợp đồng NDA',
    description: 'Mẫu hợp đồng bảo mật thông tin (Non-Disclosure Agreement) cho đối tác và nhân viên',
    category: 'Pháp lý và Giấy phép',
    status: 'Hết hiệu lực',
    version: '1.0',
    author: 'Dương Văn K',
    effectiveFrom: '01/01/2024',
    effectiveTo: '31/12/2024',
    updatedAt: '15/12/2023',
    isFavorite: false,
  },
  {
    id: '11',
    name: 'Báo cáo nghiệm thu dự án',
    description: 'Mẫu báo cáo nghiệm thu và đánh giá kết quả dự án sau khi hoàn thành',
    category: 'Quản trị Doanh nghiệp',
    status: 'Sắp hết hạn',
    version: '1.2',
    author: 'Trịnh Văn L',
    effectiveFrom: '01/03/2025',
    effectiveTo: '31/05/2025',
    updatedAt: '20/02/2025',
    isFavorite: true,
  },
  {
    id: '12',
    name: 'Phiếu đề xuất mua sắm',
    description: 'Mẫu phiếu đề xuất mua sắm trang thiết bị, vật tư văn phòng',
    category: 'Tài chính - Kế toán',
    status: 'Đang sử dụng',
    version: '3.1',
    author: 'Mai Thị M',
    effectiveFrom: '01/01/2025',
    effectiveTo: '31/12/2025',
    updatedAt: '10/01/2025',
    isFavorite: false,
  },
  {
    id: '13',
    name: 'Hợp đồng hợp tác kinh doanh',
    description: 'Mẫu hợp đồng hợp tác kinh doanh giữa công ty với đối tác',
    category: 'Khách hàng, đối tác và Hợp đồng',
    status: 'Đang sử dụng',
    version: '2.0',
    author: 'Phan Văn N',
    effectiveFrom: '15/03/2025',
    effectiveTo: '15/03/2026',
    updatedAt: '10/03/2025',
    isFavorite: true,
  },
  {
    id: '14',
    name: 'Quy trình nhập kho',
    description: 'Tài liệu quy trình nhập hàng vào kho và kiểm kê hàng hóa',
    category: 'Quản trị Doanh nghiệp',
    status: 'Hết hiệu lực',
    version: '1.0',
    author: 'Huỳnh Văn P',
    effectiveFrom: '01/01/2024',
    effectiveTo: '31/12/2024',
    updatedAt: '01/12/2023',
    isFavorite: false,
  },
  {
    id: '15',
    name: 'Phiếu đánh giá nhân viên',
    description: 'Mẫu phiếu đánh giá hiệu quả công việc nhân viên theo quý',
    category: 'Nhân sự và Lao động',
    status: 'Đang sử dụng',
    version: '2.5',
    author: 'Bùi Thị Q',
    effectiveFrom: '01/01/2025',
    effectiveTo: '31/12/2025',
    updatedAt: '28/12/2024',
    isFavorite: false,
  },
  {
    id: '16',
    name: 'Biên bản bàn giao tài sản',
    description: 'Mẫu biên bản xác nhận việc bàn giao tài sản công ty giữa các cá nhân',
    category: 'Tài chính - Kế toán',
    status: 'Đang sử dụng',
    version: '1.0',
    author: 'Đặng Văn R',
    effectiveFrom: '01/02/2025',
    effectiveTo: '31/01/2026',
    updatedAt: '25/01/2025',
    isFavorite: false,
  },
  {
    id: '17',
    name: 'Đơn xin tăng lương',
    description: 'Mẫu đơn xin tăng lương cho nhân viên đã đạt đủ tiêu chuẩn',
    category: 'Nhân sự và Lao động',
    status: 'Hết hiệu lực',
    version: '1.0',
    author: 'Tô Thị S',
    effectiveFrom: '01/07/2024',
    effectiveTo: '31/12/2024',
    updatedAt: '20/06/2024',
    isFavorite: false,
  },
  {
    id: '18',
    name: 'Hợp đồng thuê văn phòng',
    description: 'Mẫu hợp đồng thuê văn phòng làm việc, chi nhánh công ty',
    category: 'Pháp lý và Giấy phép',
    status: 'Sắp hết hạn',
    version: '2.0',
    author: 'Lưu Văn T',
    effectiveFrom: '01/01/2025',
    effectiveTo: '31/05/2025',
    updatedAt: '20/12/2024',
    isFavorite: true,
  },
];
